### ISSUE TITLE
기본 실행 질문

### ISSUE THREAD

**Issue by kimhyoil** [gyunggyung/KoGPT2-FineTuning#6]
안녕하세요 :) 
딥러닝을 시작한지 얼마 되지않은 학생입니다.
먼저 좋은 리소스 올려주셔서 감사드립니다. 
궁금한 것이 많은데 답변해주시면 정말 감사하겠습니다.

1.  Fine Tuning하는 과정에서 아래 파라미터 중 dataset은 제가 구축해야 하는 부분인가요??
`python main.py --epoch=200 --data_file_path=./dataset/All_make_lyrics_dataset.txt --save_path=./checkpoint/ --load_path=./checkpoint/auto_enter/KoGPT2_checkpoint_18500.tar --batch_size=8`

2. 해당 자료에는 checkpoint 디렉토리가 없는데 checkpoint의 데이터를 참조하는데, 이 부분도 제가 구축해야 하는 부분인가요? 추가적으로 train하지 않고 generate.py를 실행하면 모델을 아래 처럼 checkpoint에서 참조하는데 이부분도 같은 맥락인가요?
`pytorch_kogpt2 = {
	'url':
	'checkpoint/pytorch_kogpt2_676e9bcfa7.params',
	'fname': 'pytorch_kogpt2_676e9bcfa7.params',
	'chksum': '676e9bcfa7'
}` 

3. colab 환경에서 아래와 같이 실행하셨는데, `!python main.py'` 아닌 아래처럼 실행이 가능한 이유가 궁금합니다.
`main(temperature=0.9, tmp_sent = "사랑", text_size = 500, loops = 5, load_path = load_path, samples = samples)`

긴 글 읽어주셔서 감사합니다.

**Comment by gyunggyung** [comment]
안녕하세요 :)

1. 맞습니다!

2. 맞습니다!

3. colab에 최적화 시킨 코드를 만들려고 그렇게 했습니다~! 참고로 colab에서 구글드라이브 내에 있는 데이터셋을 받으려면 일반 python으로 받는 것과 경로가 다릅니다.

이 모델을 이용해서 상용 서비스를 구축할 예정이기에 모델은 공개하지 않으며, 데이터셋은 혹시 모를 저작권 문제가 있을 수도 있어서 공개하지 않았습니다 :)

감사합니다!

**Comment by gyunggyung** [comment]
참고로 지금은 데이터셋 별로 weight를 다르게 학습하는 버전 2로 업그레이드를 하면서, 코드를 정리중입니다 따라서 지금 코드를 보시면 더 혼란스러우실 수도 있을 거 같습니다 :) 해주신 3가지 질문에 답은 변함이 없으나, 지금은 아래 코드를 보시는 걸 추천드립니다.

https://github.com/gyunggyung/KoGPT2-FineTuning/releases/tag/v1.0

**Comment by kimhyoil** [comment]
답변 감사드립니다!
